#SPDX-License-Identifier: MIT-0
---
# tasks file for deploy-website

- include_tasks: ubuntu.yaml
  when: ansible_os_family == 'Debian'

- include_tasks: redhat.yaml
  when: ansible_os_family == 'RedHat'

- include_tasks: config.yaml 